### ISSUE TITLE
sporadic NoClassDefFoundError WebjarsVersion$Holder

### ISSUE THREAD

**Issue by svenackermann** [l0rdn1kk0n/wicket-webjars#48]
Hi,

I'm not sure if this is a bug in webjars or wicket-webjars or wherever.
I have a Jenkins job that builds a wicket component library which depends on wicket-webjars 0.5.3 and wicket 7.2.0. Every 2nd or 3rd build I have all unit tests failing with:
`java.lang.NoClassDefFoundError: Could not initialize class de.agilecoders.wicket.webjars.util.WebjarsVersion$Holder
    at de.agilecoders.wicket.webjars.util.WebjarsVersion.useRecent(WebjarsVersion.java:46)
    at de.agilecoders.wicket.webjars.request.resource.WebjarsCssResourceReference.<init>(WebjarsCssResourceReference.java:27)
    at mycompany.MyBasePage.renderHead
...
`

I have absolutely no idea what is causing this (and searching the web did not help). It seems very weird to me, since the class that cannot be loaded is contained in the same jar as the class that wants to load it. Also, as I said, this does not happen on every build - I can even rebuild the same source code and have a success first, but all tests failing the next time.
It never happened to me on a local build (without jenkins), but I don't do full builds very often. The jenkins build is run with JVM options `-Xmx1024m -XX:MaxPermSize=512m` and maven options `-B -T 4 clean deploy`.

I hope you have an idea how to fix that. Sorry for bothering you if that is not an issue of webjars. I have many other Jenkins jobs with similar configuration but without webjars dependency that don't have problems.

Thanks for your help,
Sven

**Comment by martin-g** [comment]
The same happens on Cloudbees (the CI used for this project. Again Jenkins behind).
The build doesn't fail anywhere else.
IMO it is some class loader related issue in Jenkins.
I'll be glad to apply patches if you find any improvements!

**Comment by svenackermann** [comment]
I just created https://issues.jenkins-ci.org/browse/JENKINS-37797, maybe the Jenkins guys have an idea.

**Comment by martin-g** [comment]
Thanks!
I hope they have an idea!

**Comment by bgooren** [comment]
Hi!

We have this issue too, but during development (on local osx machine, running eclipse; the app runs inside tomcat 8, managed from within eclipse).

The error occurs sometimes when deserializing wicket sessions on application (re-) start.
Should we not keep a reference to WebjarsJavaScriptResourceReference in our components?

Stack trace: 
```
SEVERE: Exception loading sessions from persistent storage
java.lang.ExceptionInInitializerError
	at de.agilecoders.wicket.webjars.util.WebjarsVersion.useRecent(WebjarsVersion.java:46)
	at de.agilecoders.wicket.webjars.request.resource.WebjarsJavaScriptResourceReference.<init>(WebjarsJavaScriptResourceReference.java:27)
	at com.wof.backend.pages.storage.file.browser.upload.DropzoneBehavior.<clinit>(DropzoneBehavior.java:41)
	at java.io.ObjectStreamClass.hasStaticInitializer(Native Method)
	at java.io.ObjectStreamClass.computeDefaultSUID(ObjectStreamClass.java:1787)
	at java.io.ObjectStreamClass.access$100(ObjectStreamClass.java:72)
	at java.io.ObjectStreamClass$1.run(ObjectStreamClass.java:253)
	at java.io.ObjectStreamClass$1.run(ObjectStreamClass.java:251)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.io.ObjectStreamClass.getSerialVersionUID(ObjectStreamClass.java:250)
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:611)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1630)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
	-- cut for brevity --
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at org.apache.wicket.page.PageStoreManager$SessionEntry.readObject(PageStoreManager.java:286)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1909)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at org.apache.catalina.session.StandardSession.doReadObject(StandardSession.java:1623)
	at org.apache.catalina.session.StandardSession.readObjectData(StandardSession.java:1089)
	at org.apache.catalina.session.StandardManager.doLoad(StandardManager.java:218)
	at org.apache.catalina.session.StandardManager.load(StandardManager.java:162)
	at org.apache.catalina.session.StandardManager.startInternal(StandardManager.java:356)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5268)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:587)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1798)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: there is no active application assigned to this thread.
	at de.agilecoders.wicket.webjars.WicketWebjars.settings(WicketWebjars.java:138)
	at de.agilecoders.wicket.webjars.util.WebjarsVersion$Holder.<clinit>(WebjarsVersion.java:29)
	... 195 more
```

**Comment by martin-g** [comment]
@bgooren Your issue is different than the one reported in this ticket.
Please create a new ticket. Thanks!

**Comment by svenackermann** [comment]
Hi,
I just closed https://issues.jenkins-ci.org/browse/JENKINS-37797 because the problem did not happen for some time now. Unfortunately, I don't know exactly why it's gone, but I guess it might be because of new Jenkins version. We still use wicket-webjars 0.5.3.

So if you like, you can close this. I won't do it myself because you mentioned a similar problem on Cloudbees.

**Comment by martin-g** [comment]
Cloudbees uses Jenkins!
Closing ...
